// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22.12.2025, 06:51:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/plugins/**/*.{js,ts,mjs}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/composables/**/*.{js,ts,mjs}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/utils/**/*.{js,ts,mjs}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/GameOn-DP/Desktop/rollix-nuxt-starter-fullbleed/rollix-nuxt-starter-fullbleed/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;